### ISSUE TITLE
Create separate TV and DV files for each dataset

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist-utilities#11]
Would it be possible to create one tv per dataset listed in the file (i.e. a unique dataset prefix)? 

e.g. this spreadsheet would create these tv files - 
[us_covid_q8_mappings_test.xlsx](https://github.com/user-attachments/files/16084974/us_covid_q8_mappings_test.xlsx)
[ch_indresp_w_tv.txt](https://github.com/user-attachments/files/16085000/ch_indresp_w_tv.txt)
[ch_serology_tv.txt](https://github.com/user-attachments/files/16085001/ch_serology_tv.txt)
[ch_schild_w_tv.txt](https://github.com/user-attachments/files/16085002/ch_schild_w_tv.txt)

**Comment by ollylucl** [comment]
Yep, should be possible to do this, don't see why not.

**Comment by ollylucl** [comment]
I've pushed up a commit which splits the tv files by dataset, but not the other files e.g. qv, dv, tq. Should those files be split by dataset as well?

**Comment by HayleyMills** [comment]
Great thanks, I'll test it. Yes if we can do DV as well please? Do you want me to create a new issue, or add to this one?

**Comment by ollylucl** [comment]
No need to create a new issue, just add it to this one.

**Comment by ollylucl** [comment]
The dv file is split by dataset now. Note that qv.txt and tq.txt aren't split by dataset, as you didn't ask me to do anything with them.

**Comment by HayleyMills** [comment]
Thanks tested and this is working as expected.
