### ISSUE TITLE
Names of exported files

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist-utilities#14]
The DV and TV now contain the dataset names in the filenames, as there could be more than one, for consistency, can we include the questionnaire prefix in the name (-ccs01) for the QV and TQ files?

**Comment by ollylucl** [comment]
Do you mean, that for the QV and TQ files, we should generate a file for every unique questionnaire prefix, and the title of those files should be a concatenation of the questionnaire prefix,'-ccs01', and '_qv.txt' , e.g. heaf_17_fup_4-ccs01_qv.txt?

**Comment by HayleyMills** [comment]
So it would be heaf_17_fup_4_qv.txt

**Comment by ollylucl** [comment]
Why do you have (-ccs01) in the opening message on this issue? That's confusing me.

**Comment by HayleyMills** [comment]
Ah sorry it wasn't clear it was meant to be like minus the ccs01 which I think was in the excel files, but may not need to be see #15

**Comment by ollylucl** [comment]
I think I've implemented what you asked for, the qv and tq data are now in files named after the questionnaire prefixes. If there are multiple unique values for questionnaire prefixes in the input Excel file, there will be a text file generated for each one.

**Comment by HayleyMills** [comment]
Tested and working as expected.

**Comment by ollylucl** [comment]
When I use this file as input, no files are generated, because there's no questionnaire or dataset prefix columns present.

Can I assume these columns will be present, and that this file is not correctly formatted?

[
[sws_covid_pq1_all_mappings_wip.xlsx](https://github.com/user-attachments/files/16175213/sws_covid_pq1_all_mappings_wip.xlsx)
](url)

**Comment by HayleyMills** [comment]
> When I use this file as input, no files are generated, because there's no questionnaire or dataset prefix columns present.
> 
> Can I assume these columns will be present, and that this file is not correctly formatted?
> 
> [ [sws_covid_pq1_all_mappings_wip.xlsx](https://github.com/user-attachments/files/16175213/sws_covid_pq1_all_mappings_wip.xlsx) ](url)

Yes
