### ISSUE TITLE
Edits to TQ - removal of rows for grids ($)

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist-utilities#16]
Apologies I should have included this in the criteria sooner, but for the TQ, can we remove all but one of the rows which have $ suffix (which have the same topic ID), keeping one row and deleting the $x;x. 

So for example:

whii_85_hs1_ccs01	qc_10_a-e$1;1	107
whii_85_hs1_ccs01	qc_10_a-e$1;2	107
whii_85_hs1_ccs01	qc_10_a-e$1;3	107
whii_85_hs1_ccs01	qc_10_a-e$1;4	107
whii_85_hs1_ccs01	qc_10_a-e$1;5	107
whii_85_hs1_ccs01	qc_10_f-i$1;1	107
whii_85_hs1_ccs01	qc_10_f-i$1;2	107
whii_85_hs1_ccs01	qc_10_f-i$1;3	107
whii_85_hs1_ccs01	qc_10_f-i$1;4	107

would be changed to 

whii_85_hs1_ccs01	qc_10_a-e	107
whii_85_hs1_ccs01	qc_10_f-i	107

If the topic IDs are different, then we need to keep both. So for example:

whii_85_hs1_ccs01	qc_10_a-e$1;1	108
whii_85_hs1_ccs01	qc_10_a-e$1;2	107
whii_85_hs1_ccs01	qc_10_a-e$1;3	107
whii_85_hs1_ccs01	qc_10_a-e$1;4	107
whii_85_hs1_ccs01	qc_10_a-e$1;5	107
whii_85_hs1_ccs01	qc_10_f-i$1;1	107
whii_85_hs1_ccs01	qc_10_f-i$1;2	107
whii_85_hs1_ccs01	qc_10_f-i$1;3	107
whii_85_hs1_ccs01	qc_10_f-i$1;4	107

would be changed to 

whii_85_hs1_ccs01	qc_10_a-e	108
whii_85_hs1_ccs01	qc_10_a-e	107
whii_85_hs1_ccs01	qc_10_f-i	107

Let me know if this doesn't make sense or you need more examples.

**Comment by ollylucl** [comment]
What about these cells from the input file (heaf_17_fup4_mappings):

qc_78_i$1;1
qc_78_i$2;1
qc_78_i$1;2
qc_78_i$2;2
qc_78_i$1;3
qc_78_i$2;3

There doesn't seem to be a topic associated with these? Should I just have this in the tq file:

qc_78_i

**Comment by ollylucl** [comment]
Ah my mistake, the topic is in a separate column in the Excel file. Ignore my last message!

**Comment by ollylucl** [comment]
I've pushed up a commit that deals with this issue.

**Comment by HayleyMills** [comment]
Tested using 
[whii_97_hs5_mappings.xlsx](https://github.com/user-attachments/files/16363350/whii_97_hs5_mappings.xlsx)
There was no tq.txt produced? @ollylucl

**Comment by HayleyMills** [comment]
> I've pushed up a commit that deals with this issue.

Can you assign me if you want me to test, otherwise I don't see these messages (unless you tag me).

**Comment by ollylucl** [comment]
@HayleyMills the tq file isn't produced because the code expects a certain capitalisation in the column headings, e.g. 'Question Name', not 'Question name'

We need to nail down what the format of the input file is, i.e. how many worksheets does it have, what columns are in each worksheet, do the worksheets/column headings need to have particular names, with particular capitalisation, does the order of worksheets/column headings matter, etc.

At present: worksheets can have any name, but they need to be in a particular order.
                   column headings can be in any order, but they *must* have particular names with particular capitalisation

**Comment by HayleyMills** [comment]
Thanks @ollylucl as long as this is written in the readme it doesn't matter, we can follow it. We will be using the template linked here from now on. https://wiki.ucl.ac.uk/display/CTTEAM/Mappings From previous errors I assumed if the format was not correct, it wouldn't produce any files,

**Comment by HayleyMills** [comment]
Tested and this is working as expected.
