### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ollylucl** [CLOSER-Cohorts/archivist-utilities#37]
Add something to the readme stating we “remove any rows with empty cells, NA or Derived, as they don't contain actual question names for example. Question name will always start with qc_ so it can ignore any rows which don't have question names which start with that.”

We also need to add a rule that excludes rows where the question name always starts with qc, that currently isn't being done!

**Comment by HayleyMills** [comment]
@ollylucl if it doesn't excludes rows where the question name always starts with qc - then there's no need to add it. Thanks.

**Comment by ollylucl** [comment]
Issue resolved in https://github.com/CLOSER-Cohorts/archivist-utilities/pull/38
