### ISSUE TITLE
Is it possible to add a download all button for the output?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist-utilities#41]

**Comment by ollylucl** [comment]
I pushed up a commit that adds this functionality, let me know if it meets your requirements.

**Comment by HayleyMills** [comment]
Tested, and it is working up to a point, it stops at 10 files? is that a browser thing or the script?

**Comment by ollylucl** [comment]
It's a browser limitation. I forgot that there could be more than 4 files depending on the questionnaire prefix/dataset prefix values present in the Excel file. Back to the drawing board...

**Comment by ollylucl** [comment]
What about downloading a single archive/zip file containing all the generated mapping file, would that work for you @HayleyMills ?

**Comment by HayleyMills** [comment]
@ollylucl yes that would work thanks.

**Comment by ollylucl** [comment]
@HayleyMills A link to an 'allMappings.zip' file now appears along with links to the individual mapping files.

**Comment by HayleyMills** [comment]
Tested and it's working as expected.
