### ISSUE TITLE
empty qv.txt and tv.txt produced

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist-utilities#47]
I'm confused as to what circumstances an empty tv.txt would be produced?

[mcs4_all_mappings_July24_AP_hm.xlsx](https://github.com/user-attachments/files/16659475/mcs4_all_mappings_July24_AP_hm.xlsx)
[__tv.txt](https://github.com/user-attachments/files/16659476/__tv.txt)
[mcs_07_ts_s_qv.txt](https://github.com/user-attachments/files/16659491/mcs_07_ts_s_qv.txt)

**Comment by HayleyMills** [comment]
@ollylucl thanks that all makes sense, we can make a decision about this, but the reason why I'm confused is that I thought "Any rows which do not contain all the columns listed below will not be present in the output." "Any rows with cells containing 'NA' or 'Derived', or cells that are empty, will not be present in the output, as they do not contain sufficient information." an I misunderstanding this?

**Comment by ollylucl** [comment]
I've dealt with this issue in https://github.com/CLOSER-Cohorts/archivist-utilities/pull/49.

With regards to this comment:

```@ollylucl thanks that all makes sense, we can make a decision about this, but the reason why I'm confused is that I thought "Any rows which do not contain all the columns listed below will not be present in the output." "Any rows with cells containing 'NA' or 'Derived', or cells that are empty, will not be present in the output, as they do not contain sufficient information." an I misunderstanding this?```

...the README accurately describes the behaviour we want, but the code wasn't trimming/stripping whitespace from spreadsheet cells. When cells contained whitespace (e.g. a single space) it caused the sort of odd behaviour described in the first post of this issue. A cell that contains nothing but whitespace should be treated the same as an empty cell.

I'll close this issue, but feel free to re-open it if you think we need to do more to address the issue.
