### ISSUE TITLE
How do I run the process? 

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist-utilities#6]
The process is no longer working? I uploaded the file, but there is no button to start it, and it is not starting automatically? This was working previously.

**Comment by ollylucl** [comment]
Which file are you uploading?

**Comment by HayleyMills** [comment]
Sorry realised it wasn't in the right format so it doesn't work. I there a way of it saying that or just say it's failed/error.

**Comment by HayleyMills** [comment]
[whii_all_mappings_June_24_AR_hm.xlsx](https://github.com/user-attachments/files/16055119/whii_all_mappings_June_24_AR_hm.xlsx)

**Comment by ollylucl** [comment]
The errors get output to the developer console, I'll modify the front end so they're displayed there as well!!!

**Comment by ollylucl** [comment]
I've pushed up and merged a couple of commits so that now after uploading an Excel file, the generation of the text delimited files doesn't happen automatically, instead a button is displayed, and only when this button is clicked are the text files generated.

**Comment by ollylucl** [comment]
I've pushed up and merged a commit which displays an error on the user interface if there's an error parsing the uploaded file.

**Comment by HayleyMills** [comment]
Thanks, that is working. Do you know why the file above failed? It has the same headers in the same order as the template?

**Comment by ollylucl** [comment]
I think it's because of the names of the worksheets in the file above. All the other Excel files had worksheets with the names 'QV and TV Mappings', 'DV', 'Variables', etc. The code I wrote expects those names to be present, but they're not in the above file.

Will the application have to support worksheets that can have arbitrary names?

**Comment by HayleyMills** [comment]
So does it have to have those exact tab names as well? Again I was under the impression it could just use the first tab, second tab? Having everything identical to the template is not ideal, as we need to edit the file to get it to work, which takes the same amount of time as it does to create the .txt files.  This is because everything returning from the studies now, didn't follow this new template, going forward it will be used, but for now that's not the case.

**Comment by ollylucl** [comment]
It doesn't have to have the exact tab names, but there needs to be some fixed structure to the Excel sheet; if the first tab will always have the same content, e.g. 'QV and TV mappings', the second tab will always have 'DV' content, etc. we can just select worksheets by their order, e.g. first tab for QV/TV mappings, second tab for DV mappings etc. 

However if the order of the tabs is going to change, and the tabs aren't always going to have the exact same names, that would be harder to deal with.

**Comment by HayleyMills** [comment]
No that's fine and makes sense. The first two tabs will have that content. Whichever way it works, we just need to have this included in the readme/text on the page, so we know what the input file must have.

**Comment by ollylucl** [comment]
Will the worksheets always have the same column headings, regardless of what the worksheets are called?

I'm just trying to figure out a way of uniquely identifying worksheets. The code I have at the moment might find it difficult to identify a spreadsheet by it's order in a sequence of sheets.

**Comment by ollylucl** [comment]
The thing I'm worried about is that if I write code that assumes the first tab is 'QV and TV mappings', the second tab will always have 'DV' content, etc., errors could occur if the input spreadsheets stop ordering the worksheets like that, or the code that reads the Excel file into memory doesn't preserve the order of the worksheets.

If the code doesn't select worksheets by name, I think users of the application would need to double check the output text files generated by it. In this instance, it's not ideal to select worksheets based on their order in a sequence, as opposed to by some unique identifier; there's scenarios where that could go wrong.

**Comment by HayleyMills** [comment]
Yes no problem, I don't think we need to change it.
